### PR TITLE
Update object-caching.md

### PR DESCRIPTION
**Pull request by pj-dave**
LRU stands for Least Recently Used.

### CODE REVIEW

**Comment by joshkoenig** [comment]
Thanks! Good catch!

**Comment by joshkoenig** [comment]
@pj-dave let me know if you have anything else we should include, or if there are any links from pressjitsu to add as external resources. I dig your message there, BTW. :)

**Comment by pj-dave** [comment]
Hey @joshkoenig, thanks for the merge!

I'll take you up on that link offer, we [published](https://pressjitsu.com/blog/wordpress-sessions-performance/) an article on PHP sessions recently, how locking works, how it affects performance and cachability. It might be a good idea to add that to the page caching section if you think it's valuable.

There's also one on [wp_options](https://pressjitsu.com/blog/optimizing-wp-options-for-speed/) which covers autoloading, memory usage and transients.

**Comment by joshkoenig** [comment]
Awesome stuff, man. I'll add the link to the options post since that seems on-point for object caching.

On sessions, any interest in collaborating? Our platform actually doens't allow tempfiles, so we run into this all. the. time. Our plugin solution is here:

https://github.com/pantheon-systems/wp-native-php-sessions

It'd be great if we could steer people towards a common solution. :)

**Comment by pj-dave** [comment]
Hey Josh, thanks!

Yeah we do have [something similar](https://github.com/pressjitsu/wpdb-phpsessions) but we don't deploy it to everyone on our single-node plans. The biggest issue we had with that approach is the fact that if you have a large surge in traffic, it may result in InnoDB tablespace being wasted and GC doesn't reclaim it unless you OPTIMIZE (which can be slow) or TRUNCATE the whole table (which can affect visitors online).

That said, the largest problem we've seen so far is plugins blindly initializing sessions and thus killing cacheability. We've seen this with many popular themes and plugins, even from highly talented and respected developers -- just a couple of days ago we reported this issue to the devs behind Easy Digital Downloads, they promised to fix it soon-ish. So steering developers away from starting a PHP file with `session_start()` will have a much bigger overall impact than steering users to non-temp-file storage for sessions.

But your solution looks pretty cool and somewhat sophisticated. I'll install it locally and play around, will report back if I find any troubles. Thanks for the link!

**Pull request merged**
